### ISSUE TITLE
Testing file type detection based of file name

### ISSUE THREAD

**Issue by HiPhish** [junegunn/vader.vim#100]
I have a plugin for Jinja templates and among other things it detects files with multiple file extensions like `foo.html.jinja` as `html.jinja`, but only if the type is one Vim knows about (`foo.bar.jinja` would be recognised as just `jinja`). Here is the plugin: https://github.com/HiPhish/jinja.vim

My first Vader test looks like this:
```vader
Execute (A simple file extension):
  silent file foo.jinja
  filetype detect

Then:
  AssertEqual 'jinja', &filetype
```

This works just fine. However, when it comes to two extensions things don't work out anymore:
```
Execute (Two file extensions):
  silent file foo.html.jinja
  filetype detect

Then:
  AssertEqual 'html.jinja', &filetype
```

The `&filetype` variable is just `jinja` (it's the same without the `silent` as well). When I tried these steps manually in a new Vim instance everything worked, so my guess is that the issue must lie in Vader. Any ideas?

**Comment by junegunn** [comment]
> When I tried these steps manually in a new Vim instance everything worked

Not for me. 1. Installed your plugin, 2. `file foo.html.jinja`, 3. `filetype detect`, but I'm getting `jinja`.

**Comment by HiPhish** [comment]
Now this is odd, it does work for me in Vader as well. I looks like I had to restart Vim before running Vader. That's really annoying if I want to do test-driven development.

But I have now also find out that the reason it works only for me is that I had an autocommand for HTML files in my settings, so what you found is an unrelated problem. I'll get to fixing it. Thank you.
