### ISSUE TITLE
Autocommands caused command to abort

### ISSUE THREAD

**Issue by christianrondeau** [junegunn/vader.vim#112]
I will try to provide more details, here's what I have up to now:

1. Run tests using `:Vader %`
2. Some tests fail; I'm in a new tab, with the test results and the quickfix window. Focus is in the quickfix window.
3. I press <kbd>q</kbd>
4. I receive the following messages: `E855: Autocommands caused command to abort`
5. Both the quickfix window AND the test results stay opened, but my *original* tab gets closed!
6. Further attempts to use <kbd>q</kbd> give me `E784: Cannot close last tab page` (which makes sense I guess)

Note that if I switch focus to the test results window, <kbd>q</kbd> behaves as expected. Same thing if all tests are successful.

I did not yet try to run without plugins, so maybe there's a conflict. I'll report it here when I have time.

(I'm in love with Vader, it's awesome)

**Comment by christianrondeau** [comment]
I confirm that there is a conflict with another plug-in... Running `vim - Nu` with a vader-only vimrc works. 

I'll investigate and close when I find the culprit.

**Comment by christianrondeau** [comment]
I had some time to diagnose this. It seems that the culprit is when `set hidden` is enabled in `vimrc`... which surprises me, as I think this is a very common option.

I can reproduce by starting with `vim -Nu vimrc-with-only-vader-rtp`, typing `:set hidden`, running `:Vader` in a failing vader test and then pressing <kbd>q</kbd>. Doing the same thing without `hidden` closes the new tab as expected.

**Comment by junegunn** [comment]
Thanks for looking into it. Yeah, I can reproduce locally. Turned out that the code added in https://github.com/junegunn/vader.vim/commit/ceba9db6aed6e33b36480d6bf206be6e70779fa4 is causing the error. Interestingly, I don't get any error with an older version of Vim, which I used when I added the code. There must have been a change in Vim that makes the code no longer valid. I'll see what I can do.

**Comment by christianrondeau** [comment]
No problem, in the meantime I applied your suggestion in #113 which means I don't have the *quickfix* window, therefore no issue :) If you didn't magically fix that today, I might take a look later, so that I can help and not only leech your time!

**Comment by christianrondeau** [comment]
I didn't understand why we wanted to swich tab when hiding the buffer (it already closes the tab when all buffers of this tab are closed), so I took a look at #99.

Here are some cheap solutions:

1. Make the <kbd>q<kbd> mapping first switch to the previous tab, *then* remove the vader result tab (avoiding the need for BufHidden and recursive autocmds). When you use the tab manually, I would expect VIM to do the same as with any other tabs anyway.
2. Since it seems to work when I'm *not* in the quickfix window, another cheap fix would be to switch to the results buffer first, and then execute `tabclose`

Option 1 feels "less hacky", I can provide an implementation if you want. I'll see if I can get something working quickly.

**Comment by christianrondeau** [comment]
Here you go, I have provided an implementation (option 1) that achieves the same goal as stated in #99, without using `BufHidden`. Unless there's another use case than pressing <kbd>q`</kbd> which should behave differently than VIM does by default, this should cover the basics pretty well.

In my humble opinion, closing the vader results tab using `:tabclose` or `:q` should keep default VIM behavior.

Hope that helps!

**Comment by junegunn** [comment]
Thanks!

**Comment by christianrondeau** [comment]
Yay! I helped :)
