### ISSUE TITLE
Add an open for disabling opening the quickfix window

### ISSUE THREAD

**Issue by w0rp** [junegunn/vader.vim#130]
When there are errors in Vader results, when running Vader inside of Vim, the quickfix is opened with the lines for Vader errors. I personally just want to see the results. I would like an option to be added, which can be off by default, for preventing the quickfix window from being opened.

**Comment by junegunn** [comment]
Duplicate of #113. We haven't added `-bar` yet though.

**Comment by blueyed** [comment]
JFI: `-x` is implemented already (to stop after the first failure)

**Comment by w0rp** [comment]
In my case, this works fine for me.

```vim
function! RunVader() abort
    Vader
    cclose
endfunction

" Map F9 to running Vader tests.
noremap <buffer> <F9> :call RunVader()<Return>
```
