### ISSUE TITLE
Advice on running Vader in the Windows commandline

### ISSUE THREAD

**Issue by w0rp** [junegunn/vader.vim#138]
Hello! I have been using Vader for testing my plugin for ages, and I've recently been setting up AppVeyor, so I can run tests in Vim 8 on Windows. I have managed to get that set up okay, but I have had some trouble running Vader from a Windows commandline myself. I've been trying to run the same tests with the same Vim version and vimrc file in a standard Windows console window, on Windows 10, inside a VirtualBox VM.

The problem I've been having is that it looks like using `"+Vader! test/some_vader_test.vader"` as an argument for vim.exe does seem to run something, but the console appears to be cleared as soon as Vim exits. Do you have any advice for settings that can be changed either in Vim or in the terminal so I can see the output of tests?

**Comment by blueyed** [comment]
Maybe VADER_OUTPUT_FILE helps here, as with Neovim?

**Comment by w0rp** [comment]
Thanks! That works for me.

I had to create the file for the environment variable first, as Vader uses a `filewritable` check which returns `0` if the file doesn't exist. Maybe that could be changed at some point, so files which don't yet exist can be written.

This example works for me.

```batch
@echo off

set VADER_OUTPUT_FILE=%~dp0\vader_output
type nul > "%VADER_OUTPUT_FILE%"
C:\vim\vim\vim80\vim.exe -u test/vimrc "+Vader! test/test_regex_escaping.vader"
type "%VADER_OUTPUT_FILE%"
del "%VADER_OUTPUT_FILE%"
```

**Comment by blueyed** [comment]
Cool!

> filewritable check

Makes sense: https://github.com/junegunn/vader.vim/pull/139

I wanted to have AppVeyor integration for Neomake myself, so I might take a look at how you did it eventually.

**Comment by blueyed** [comment]
btw: is there something similar to `/dev/stderr` that could be used, i.e. so that you do not have to create a file at all?

**Comment by w0rp** [comment]
There's only `CON`, and I doubt it would actually work. Windows sucks.

**Comment by blueyed** [comment]
I've given AppVeyor a try now, too: https://github.com/neomake/neomake/blob/appveyor/.appveyor.yml

But it does not output anything anymore, since the tests failed already.

    C:\vim\vim\vim80\vim.exe -u tests/vim/vimrc "+Vader! tests/appveyor.vader"
    Vim: Warning: Output is not to a terminal
    Command exited with code 1

I guess it needs to do the equivalent of saving the exit code, without causing the line to fail, then output the logfile, and afterwards exit with the exit code from Vim.

**Comment by blueyed** [comment]
@w0rp 
Can you provide more feedback, please? (I will of course add also some license to the .appveyor.yml if you request it, before merging it into Neomake)

**Comment by w0rp** [comment]
Check out what a recent build did for some information. I haven't made it run basically any tests yet, I've got a lot of work to do on fixing various tests so they pass on Windows. (Mostly issues with Linux programs being run, or filesystem issues.) https://ci.appveyor.com/project/w0rp/ale/build/1.0.42

However it is that AppVeyor is set up, Vader seems to work okay there. This Batch script works okay for me, for running the tests in my Windows VM. https://github.com/w0rp/ale/blob/master/run-tests.bat
