### ISSUE TITLE
Tests with multiple filetypes

### ISSUE THREAD

**Issue by kkoomen** [junegunn/vader.vim#196]
Hi.

First of all, love the plugin! Testing my vim plugin is super easy and I love the easy usage!

I am in a case where I have tests for the `javacript` filetype but I'm having the exact same tests for the `jsx` filetype. For now I have them as separate test files, but do you have an idea if I can maybe simplify this since these are the exact same tests?

For example, I presume this is not possible, but I am looking for something like: `Given javascript, jsx (example function)`

If this option is not possible or anything else, that's fine, since I do think given 1 filetype is logical.

**Comment by blueyed** [comment]
Do you need the tests to be duplicated then after all?

You could also try using symlinks, but I assume the test headers are different.

It might make sense to just have a single test to check that it behaves well for both filetypes in general (e.g. the loading/handling for that filetype), and then just test with the primary one.

FWIW `set filetype=javascript.jsx` might also be something interesting in this regard (i.e. activate both filetypes).

**Comment by kkoomen** [comment]
I can do `javascript.jsx` but I have 4 filetypes here which are the same in tests: `javascript`, `jsx`, `typescript`, `tsx`, so how do I solve this case?

**Comment by kkoomen** [comment]
I got it, thanks.
