### ISSUE TITLE
Disable folding during tests ?

### ISSUE THREAD

**Issue by elythyr** [junegunn/vader.vim#197]
Hi,

I just start using Vader, so it might just be because I'm not used to it but I had an unfortunate issue that took me some time to figure out.

I was deleting a line in an Execute block and instead of deleting only one line multiple lines were deleted.
I couldn't figure out why...
When I ran Vader in an isolated context, no problem.
So I started to look for which plugin was creating an issue.
At the end, it was the plugin that provide me with a foldexpr function.

Meaning that while I'm writing my tests, folding is off.
But when they are executed, folding is on and I was deleted a fold instead of a line.

It might be a good idea to use `set nofold` before execute a test.
In the same time, it kind of make sense to test with them.
So maybe just add some kind of warning about it, like in the `Known Issues` section of the readme.

**Comment by blueyed** [comment]
Don't you use a minimal vimrc for your tests in the first place?
Also I run Vader in general using `--noplugin`, sourcing the tested plugin explicitly, and/or some temporary home (`$HOME`) - to not load things from `~/.vim/plugins` etc.

**Comment by elythyr** [comment]
The "real" tests are indeed launched in an isolated context.
But when I'm writing them I like to be able to launch them right inside vim with [vim-test](https://github.com/janko/vim-test), which is where I got my problems.
The fact is that it's even interesting to know about possible conflicts with other plugins/functionalities.
For instance, I was testing the fact that when I handle a `.patch` file inside vim, my cursor stay in the expected position.
After this folding problem I now realize that I have to be careful about folding when I will change the buffer.

Anyway, it was more about letting a trace for anyone to find in a later date.
I didn't find any information about it while I was searching so it could be of some use one day.
If it make it's way to `Known Issues` it's even more accessible, otherwise it doesn't really matter :)

**Comment by blueyed** [comment]
> Anyway, it was more about letting a trace for anyone to find in a later date.

Thanks! :)
