### ISSUE TITLE
Test files should be encapsulated

### ISSUE THREAD

**Issue by kkoomen** [junegunn/vader.vim#198]
I haven't looked into the vader code itself, but I am deeply wondering how tests are being ran, because it seems like all the tests are ran using 1 single vim instance, which makes sense, but I am expecting a full 'reset' for each test file.

**The issue**
When I set: `let g:myvar = 1` that this is enabled for every test file that runs after it, while I expect this value to be set specifically for this test (or at max the current test file), since I have enabled this just for the `Do (...)` block. The reason I am creating files is to separate different tests and encapsulate the logic. It's not relevant for test file B to have settings persisted from test file A.

**Proposed solution**
Encapsulate every test file and reset all settings for each file.

**Comment by blueyed** [comment]
Yes, tests are read from multiple files, but then joined / parsed together.
To have them separate you have to run them separately.
In Neomake I have a set of "main" tests, but then also a bunch of "isolated" ones, which get run by themselves.

**Comment by blueyed** [comment]
To change globals, look at `Save` and `Restore`.

**Comment by kkoomen** [comment]
@blueyed So to confirm: If I have: `fileA.vader` and `fileB.vader` I should do `vim "+Vader! fileA.vader"` and then `vim "+Vader! fileB.vader"` instead of `vim "+Vader! fileA.vader fileB.vader"`?

**Comment by blueyed** [comment]
Yeah.
