### ISSUE TITLE
Test script local function s: that is meant to be invoked from <sid> map call

### ISSUE THREAD

**Issue by cirosantilli** [junegunn/vader.vim#52]
A common design pattern to hide functions while exposing maps is to use in the script file:

```vim
function s:F()
  " do something
endfunction

nnoremap f :call <sid>F()<cr>
```

There may however be functions which have untestable side effects: in my case opening a browser at a given URL.

So I split it up as:

```
function s:GetUrl()
endfunctoin

function s:OpenBrowser()
  call <sid>OpenBrowser(<sid>GetUrl())
endfunctoin

nnoremap f :call <sid>OpenBrowser()<cr>
```

In that case, it would be fine if I could test just `GetUrl`. Is there a way of doing that without exposing it (i.e. removing the `s:`).

Similar for Vrunner: http://stackoverflow.com/questions/15595505/unit-testing-vim-script-local-functions-with-vimrunner

**Comment by junegunn** [comment]
I've never tried doing it. The answer from Ingo Karkat from the link you posted, parsing the output of `:scriptnames`, probably is the only viable way to do it. Should Vader provide a helper function for that? I don't know. The method seems a bit hacky to me, and whether to test private methods or not has always been a very controversial topic.
