### ISSUE TITLE
vim process is not terminating

### ISSUE THREAD

**Issue by rstacruz** [junegunn/vader.vim#53]
When doing `vim -Nu <(....) +"Vader! test/*" >/dev/null`, it seems that the process doesn't exit until I press enter.

This is an issue because the process lingers on in Travis-CI.

**Comment by rstacruz** [comment]
hmm, actually this looks like an issue cause i'm invoking it as `bash -c "env HOME=/dev/null vim ... >/dev/null"`... sorry about that!

**Comment by junegunn** [comment]
No problem.

**Comment by rstacruz** [comment]
Okay, actually I can seem to reproduce this consistently.

vimrc:

	@echo "filetype off" > $@
	@echo "set rtp+=$<" >> $@
	@echo "set rtp+=." >> $@
	@echo "filetype plugin indent on" >> $@
	@echo "syntax enable" >> $@

**Comment by rstacruz** [comment]
at the very least, maybe the `HOME=/dev/null` suggestion in the README should be reconsidered :)

**Comment by junegunn** [comment]
Ah, yeah, that `HOME=/dev/null` suggestion was added by a PR (#40), and I completely forgot about it because I was not actually using it in my projects. I can reproduce the error.

@blueyed Hi, can you look into this?

**Comment by blueyed** [comment]
I have not investigated, but I am not seeing this issue.

I am using `HOME=/dev/null $(VIM_BIN) -XNu vimrc -i viminfo` with the following
`vimrc` (from a `test` dir):

    filetype off
    set runtimepath+=vader.vim
    set runtimepath+=..
    filetype plugin on
    syntax enable
    set hidden

    set colorcolumn=75

    " Easier for window numbers (incrementing).
    set splitbelow

**Comment by junegunn** [comment]
@blueyed I realized that it works with the system default Vim of OS X, which is 7.3, but it doesn't work with Vim 7.4 that I installed with Homebrew.

@rstacruz Removed `HOME=/dev/null` from the README page. Thanks for the report!

**Comment by rstacruz** [comment]
It also behaves that way on Travis: https://travis-ci.org/rstacruz/vim-css-shorthand/builds/64242752

> No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
>  ran for 10 min 14 sec

**Comment by blueyed** [comment]
I think this happens because of `E138: Can't write viminfo file /dev/null/.viminfo!`.

If you specify a viminfo file to use additionally, it might work:

    env HOME=/dev/null vim -Nu vimrc-test -i viminfo +"Vader! test/*"
