### ISSUE TITLE
testing script functions?

### ISSUE THREAD

**Issue by rstacruz** [junegunn/vader.vim#54]
How can i test `s:` functions?

```vim
function s:get_message()
  return "hi"
endfunction
```

**Comment by junegunn** [comment]
Related:
- https://github.com/junegunn/vader.vim/issues/52#issuecomment-81069944
- http://stackoverflow.com/questions/15595505/unit-testing-vim-script-local-functions-with-vimrunner

It's possible to call script-local functions with the script number of the file found from the output of `:scriptnames`. e.g. `call <SNR>2_esc('hello')` But vader currently does not provide a helper function for doing that.

**Comment by rstacruz** [comment]
wicked!
