### ISSUE TITLE
`Execute lang` doesn't work

### ISSUE THREAD

**Issue by rstacruz** [junegunn/vader.vim#55]
...not that I need it to, but maybe it should be removed from the docs if it's not supported.

```
Execute css:
  exe "normal adiv {\<Enter>"
```

```
    (11/11) [EXECUTE] (X) Vim:E492: Not an editor command: css << __VADER__LANG__IF__
      > /private/var/folders/5y/190gjd_j2c5bfkn563dk2xdr0000gn/T/v48zTKd/2, line 1
```

**Comment by junegunn** [comment]
`Expect something` is for testing foreign language interface, such as ruby, python, lua, etc. See the examples [here](https://github.com/junegunn/vader.vim/blob/master/test/feature/lang-if.vader). The lang part of the label is actually the name of vim command Vader uses to test the following code and there's obviously no css command.

**Comment by rstacruz** [comment]
oops, i guess i misread `Expect` in the docs as `Execute` and thought that it can accept a filetype (even if it doesn't make sense) :P sorry!
