### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by pwntester** [junegunn/vader.vim#59]
Thanks for the plugin it looks exactly what I was looking for and its great it does not depend on other languages/tools!

Im wondering if the following things are possible:
- test omnicompletion functions
- test neomake/syntastic outputs in quickfix list
- test asynchronous commands which output in the quickfixlist (neovim)
- reuse GIVEN blocks. I want to use the same block for different tests and dont want to repeat the text (its large block). Can it be outsourced to an external file and then do something like GIVEN fixtures/mytext.txt

Thanks in advance!
A

**Comment by junegunn** [comment]
- test omnicompletion functions
    - Yes, see https://github.com/junegunn/vim-emoji/blob/master/test/emoji.vader#L48-L60
- test neomake/syntastic outputs in quickfix list
    - neomake, if it's asynchronous, then no. On the other hand, Syntastic AFAIK is synchronous, so it should be possible though I haven't tried.
- test asynchronous commands which output in the quickfixlist (neovim)
    - No. Vader is basically a macro player (`q` / `@`), and macros cannot simulate asynchronous user interaction.
- reuse GIVEN blocks. I want to use the same block for different tests and dont want to repeat the text (its large block). Can it be outsourced to an external file and then do something like GIVEN fixtures/mytext.txt
    - `Include: fixtures/mytext.txt`
