### ISSUE TITLE
travis CI is broken

### ISSUE THREAD

**Issue by albfan** [junegunn/vader.vim#65]
I try to test your master and it fails. Travis team inform on environment changes but don't know how to fix.

> vim: error while loading shared libraries: libruby.so.2.2: cannot open shared object file: No such file or directory

**Comment by junegunn** [comment]
Thanks for the ping. I'll see what I can do.
(Maybe related: https://github.com/junegunn/vim-plug/issues/207#issuecomment-168435551)

**Comment by albfan** [comment]
Yes ruby 2.2 is installed so LD_LIBRARY_PATH should be a fix. I will check because vim-ruby is blacklisted and vim-nox is a tiny version of vim and lack some features needed for vader
