### ISSUE TITLE
Insert/put text in buffer goes wrong, and is consistent between environments

### ISSUE THREAD

**Issue by jreybert** [junegunn/vader.vim#68]
In my test suite, I need to:
* open a buffer, let's call it `magit` (this buffer has special treatment when opening)
* and then, alternate in this buffer
  * perform some command in `Execute():` mode
  * write some words/line

I tried to alternate `Execute():` and `Do():` modes, but when I come back to `Execute():` mode, I am not in `magit` buffer, but in some vader buffer.

I tried to insert text in `Execute():` mode using:
* `:put ="some text"`
* `call append(line('.'), ["some text"]`
* `:read some_input_file`

For some insert, the inserted line is inserted twice. For example, if I want to insert

> Insert this peculiar line

I get:

> Insert this peculiar lineInsert this peculiar line

For some other input, everything is OK.

Until now, it was OK because this double insertion was the same, for every evironment (an environment depends on [linux version / bash version / vim/nvim version] ). But for the last test I am writing, it does not produce the same output on all environments.

Do you have some hints? I can provide you a way to reproduce this in a quite simple way.

Thanks

**Comment by junegunn** [comment]
Can you provide a complete vader snippet I can use to reproduce the problem you're describing?

**Comment by jreybert** [comment]
Oooops, I am very sorry... After a deep debug, problem was in my test. put/append/read lines in a buffer are working like a charm :)

Anyway, there is still the problem with successive Execute and Do modes, but it does not block me. I do not know if you want we go further in this direction.

**Comment by junegunn** [comment]
Each Do and Execute block constitutes a single test case and the test buffer is "reset" between them. If you want a mixture of Execute and Do, you'll have to use `normal!` (or `normal`) in Execute block.

```vader
Given:
  foo

Do:
  gUU

Expect:
  FOO

Execute:
  call setline('.', repeat(getline('.'), 2))

Expect:
  foofoo

Execute:
  call setline('.', repeat(getline('.'), 2))
  normal! gUU

Expect:
  FOOFOO
```

(If you want the same Vimscript to be applied to the subsequent test cases, you can use `Before` block.)
