### ISSUE TITLE
Trying to test completion of LaTeX files

### ISSUE THREAD

**Issue by lervag** [junegunn/vader.vim#70]
I've begun to use Vader to test [vimtex](https://github.com/lervag/vimtex). I really like it, but I have some difficulties. One particular problem is when I try to add tests for the omnicomplete function. This function requires me to parse a LaTeX project, which often includes other files. For this to work, I begin with parsing the main LaTeX file.

The problem seems to be that the `[Vader workbench]` is never saved as a file, and so vimtex functions that parse files fail because of stuff like `readfile(...)`.

This seems to be a problem for more than just the completion. A lot of vimtex functionality depends on parsing either LaTeX files or auxilliary files. And parsing always starts from the main LaTeX file (a LaTeX project may consist of several files, but one of them will always be the "main" file).

Do you have any suggestions?

**Comment by junegunn** [comment]
Hmm, is it viable to save it as a temporary file like follows?

```
Before (Save workbench buffer as file):
  w /tmp/buffer
  silent e /tmp/buffer
  setf tex

After (Remove temporary file):
  bd! /tmp/buffer
  call delete('/tmp/buffer')

Given tex:
  \begin{document}
  \end{document}

Execute:
  Log getline(1, '$')
  Log [expand('%:p'), &filetype]
```

**Comment by lervag** [comment]
I think it might work, thanks. I'll report back after some testing!

Btw: Would it be possible to add some more descriptions to the available commands in the docs, e.g. `Log`, `Save` and `Restore`?

**Comment by junegunn** [comment]
Yeah, the doc needs some improvement, I'll try to look at it when I get some time.

**Comment by lervag** [comment]
It works with the following code:

```
Before:
  call delete('/tmp/vader', 'rf')
  call mkdir('/tmp/vader')
  call system('touch /tmp/vader/fig_1.tex')
  call system('touch /tmp/vader/fig_2.tex')
  w /tmp/vader/test.tex
  silent e /tmp/vader/test.tex
  setf tex

After:
  w
  bd! /tmp/vader/test.tex

Given tex:
  \includestandalone{

Do:
  A\<c-x>\<c-o>\<c-n>}

Then:
  AssertEqual
    \ '\includestandalone{fig_2}',
    \ readfile('/tmp/vader/test.tex')[-1]
```

I was just wondering if I could simplify this. I couldn't find a way myself, but perhaps I am missing something?

**Comment by junegunn** [comment]
It's going to be nice and easy once #71 is landed, right?

**Comment by lervag** [comment]
Yes. Or, if not, I'm starting to understand the concepts better now, and I think both with and without #71 I will manage just fine. Thanks!
