### ISSUE TITLE
Test input completions

### ISSUE THREAD

**Issue by lervag** [junegunn/vader.vim#74]
I'm trying to test input completions for tex files with vimtex. After a lot of fiddling, I've ended up with this:

```
Before:
  silent e env/trivial.tex

After:
  w! expect.tex
  bd! env/trivial.tex

Do:
  cse\<c-n>\<cr>

Then:
  Log readfile('expect.tex')
  Log readfile('env/test2.tex')
  Assert
    \ readfile('expect.tex')
    \ == readfile('env/test2.tex')
  call delete('expect.tex')

Before:
After:
```

This sort of works, but I get a strange error:

```
    (1/1) [     DO] (X) Vim(let):E117: Unknown function: <SNR>22_input_complete
      > function <SNR>22_vader[5]..vader#run[45]..<SNR>23_run[45]..vader#window#replay[2]..vimtex#env#change_prompt, line 10
```

In vimtex, I use a script local function for the input completion candidates. For some reason, this seems to be problematic for Vader.

By the way, I am hoping that the `Given: FILE` suggested in #71 might simplify the above procedure and perhaps also fix this problem.

**Comment by junegunn** [comment]
I have a WIP patch lying on my drive for that. Haven't had a chance to finish it up. You can try it and see if it helps.

https://gist.github.com/junegunn/03e51de7b0de2efb33e19566da2864dd

It'll make the above code simpler, but I don't think it'll help with this issue. My guess is that you'll have to use autoload function.

**Comment by lervag** [comment]
Thanks, I'll try the WIP when I get the time.

In the meantime, I'm wondering if you have any proposed workflows for writing tests for completion or similar that requires to parse a project. E.g., in LaTeX project one typically uses multiple files, and completion should take into account the content of all the files. Thus, I want to create a Vader test that consists of at least two `.tex` files and that will parse the files to gather completion candidates.

In particular, my code relies on files being saved to disc. I've tried to use `After` and `Before` to toggle the buftype and write the workbench, but then Vader just hangs. E.g., I try the following:

```
Before:
  set buftype=
  silent w!

After:
  set buftype=nofile

Given tex:
  \newglossaryentry{afs}{test}
  \gls{

Do:
  jA\<c-x>\<c-o>\<c-n>

Expect tex:
  \newglossaryentry{afs}{test}
  \gls{afs}
```

Here the omni-completion should read the file from disk, parse it for `newglossary` entries and autocomplete it. But this does also not work.

I am thinking that there could/should be some way to achieve what I want with the current implementation, but I can't seem to figure it out...

**Comment by junegunn** [comment]
If your requirement cannot be satisfied with Vader constructs, which are indeed designed for relatively simple cases, you'll have to write your test code in Vimscript in Execute blocks as follows.

```vim
Execute:
  " Open a file in a project
  e some-project/some-file

  " Instead of Do blocks...
  execute "normal! i\<c-x>\<c-o>\<c-n>"

  " Assertions
  AssertEqual foo, bar

  " Another file
  e some-project/some-other-file

  " ...
```

**Comment by lervag** [comment]
I found something that works! My previous example failed because I forgot to delete the workspace file. This works:

```vim
Before:
  set buftype=
  silent w!

After:
  set buftype=nofile
  silent call delete('[Vader-workbench]')

Given tex:
  \newglossaryentry{afs}{test}
  \gls{

Do:
  jA\<c-x>\<c-o>\<c-n>

Expect tex:
  \newglossaryentry{afs}{test}
  \gls{afs}
```

**Comment by lervag** [comment]
By the way: For some reason, I had to make the input complete function global in scope, instead of local to script.

In any case, with this I think I can get most of my remaining tests working.
