### ISSUE TITLE
After is not run in case of error in Execute

### ISSUE THREAD

**Issue by blueyed** [junegunn/vader.vim#78]
I am trying to set a variable for every `Execute` block, and restore it in a `_setup.vader` file:

```
" Setup and helpers for all tests.

Before:
  if exists('g:neomake_verbose')
    echom "BEFORE: save" g:neomake_verbose
    let g:save_neomake_verbose = g:neomake_verbose
  endif
  let g:neomake_verbose = 3

After:
  echom "AFTER: exists:" exists('g:neomake_verbose')
  if exists('g:save_neomake_verbose')
    echom "AFTER: restore" g:neomake_verbose "=>" g:save_neomake_verbose
    let g:neomake_verbose = g:save_neomake_verbose
    unlet g:save_neomake_verbose
  else
    echom g:neomake_verbose
    unlet g:neomake_verbose
    echom 'exists?' exists('g:neomake_verbose')
  endif

Execute:
  echom 'Execute: exists?' exists('g:neomake_verbose')
  command! -nargs=* RunNeomake Neomake <args>
    \ | while len(neomake#GetJobs()) | sleep 50m | endwhile
```

But although the var does not exists at the end of `After` it will be set after the test has finished.

I have found the `Save` and `Restore` commands, but they behave the same.
It looks like what `Before` does will be considered the global/initial state that gets restored at the end?!

**Comment by junegunn** [comment]
> But although the var does not exists at the end of After it will be set after the test has finished.

I'm not sure if I follow, Before and After block work as expected.

```
Before:
  Log 'before'
  let g:xxx = 1

After:
  Log 'after'
  unlet g:xxx

Execute (1):
  Log 'g:xxx = '.g:xxx

Execute (2):
  Log 'g:xxx = '.g:xxx
```

After executing the script, `g:xxx` no longer exists.

**Comment by blueyed** [comment]
Weird.

After all it might be just related to / caused by `After` not being called in case on an error in `Execute`?!

```
Before:
  Log 'before'
  let g:xxx = 1

After:
  Log 'after'
  unlet g:xxx

Execute (1):
  Log 'g:xxx = '.g:xxx

Execute (2):
  Assert 0
  Log 'g:xxx = '.g:xxx
```

**Comment by junegunn** [comment]
Oh right, I don't think I intend it. Let me fix that.

**Comment by junegunn** [comment]
Let me know if it helps.

**Comment by blueyed** [comment]
Thanks!

What do you think about calling `Restore` always automatically?
Otherwise it's not guaranteed that values from `Save` would be restored.
On the other hand it makes it easier to inspect values on test failures maybe?!

It's not really relevant for tests on CI, but if you `Save &shell`, it makes sense to restore it when using Vader interactively.

**Comment by junegunn** [comment]
> What do you think about calling Restore always automatically?

After all the tests are finished, right? I think it's a good idea.
