### ISSUE TITLE
Call parent Before/After method from Before/After?

### ISSUE THREAD

**Issue by blueyed** [junegunn/vader.vim#79]
You might want to have a global `Before`/`After` section in you global `_setup.vader` file, but then some additional `Before`/`After` in your actual test files.

While a workaround seems to be defining functions for the global setup/teardown, I wondered if having commands like `ParentBefore`/`ParentAfter` would be feasible?

**Comment by junegunn** [comment]
Well, I can certainly understand the logic behind your suggestion, but adding more constructs will inevitably make Vader more complex, and I'd prefer to keep it small. Like you said, we can define functions in `Execute` block to reduce code duplication, and I'm fine with the approach. Vader is a simple test framework for simple requirements. If you find yourself keep having troubles writing test cases with Vader, you may have reached the point where Vader is no longer the best tool for your requirement.

**Comment by blueyed** [comment]
Fair enough.
I can totally see your point, but wanted to suggest it anyway and/or make sure that I'm not missing something.
Thanks!
