### ISSUE TITLE
":version" output might not be fully visible on Travis

### ISSUE THREAD

**Issue by blueyed** [junegunn/vader.vim#90]
https://travis-ci.org/neomake/neomake/jobs/164526849#L595:

The first line of the `:version` output is not fully visible:
```
…
1                             Neomake: Invalid maker name: non-existentpiled Sep 26 2016 21:23:11)
Compiled by vim-testbed
Huge version without GUI.  Features included (+) or not (-):
```

I wonder if there should just be an extra `\n` at the beginning to cope with this?!

**Comment by junegunn** [comment]
It looks like ANSI escape sequences from Vim is interfering with the display.

In one of my tests, I redirect stdout of Vim to `/dev/null` which seems to help, right?

https://travis-ci.org/junegunn/vim-easy-align#L188-L189

**Comment by blueyed** [comment]
Thanks, using this method fixed it.
