### ISSUE TITLE
Feature: option to abort tests on first failure

### ISSUE THREAD

**Issue by blueyed** [junegunn/vader.vim#94]
This corresponds to pytest's `-x` flag: it would abort the test suite `:Vader` run after the first failure.

I could imagine using it with `:Vader! -x …` / `:Vader! --exitfirst …`.

`--maxfail X` might also be useful, but might be too much.  But it means that `-x` could be implemented as `--maxfail 1`.

**Comment by junegunn** [comment]
Makes sense, and it should be fairly easy to implement.

FYI, my current priority is #69, to find a way to extend Vader for asynchronous features as I need it for vim-plug. I'll try to look into your suggestions after that.
