### ISSUE TITLE
Add ! to function definition

### ISSUE THREAD

**Issue by lervag** [junegunn/vader.vim#95]
I just updated my plugins, and it brought me this warning:

```
Error detected while processing /home/lervag/.vim/bundle/vader.vim/plugin/vader.vim:
line   35:
E122: Function <SNR>82_vader already exists, add ! to replace it
```

I don't know any reason _not_ to add the `!`, but perhaps there is some reason I don't know of?

**Comment by junegunn** [comment]
No reason. I'll update the function. The error you saw was due to https://github.com/junegunn/vader.vim/commit/66e2f7d1cf642c60a4b539b2e4441d45661818a1 and it should be temporary.

**Comment by lervag** [comment]
Great, thanks!
