### ISSUE TITLE
When multiple Given blocks are provided (even in separate files) with `[v`], the second always starts as empty (Travis/Vim 7.4)

### ISSUE THREAD

**Issue by christianrondeau** [junegunn/vader.vim#96]
Here are some pretty simple reproduction steps. I have tried many things, and finally ended up having to files exactly the same, one succeeding, the other one failing. It works on my machines (both on Windows and on Linux), the issue only happens on Travis. Here are some information:

The branch and folder where you can see the two identical files: https://github.com/christianrondeau/vim-base64/tree/vader-report-96/tests (`visual-decode.vader` and `visual-encode.vader`)

The specific build where you can see it fail: https://travis-ci.org/christianrondeau/vim-base64/builds/169624871

The VIM version is `7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32), Included patches: 1-52` and it also failed with version `7.3` (the one built-in Travis)

I guess it's related to this specific VIM version, but otherwise everything works. Any idea?

**Comment by junegunn** [comment]
I'm not sure what's going on. How about adding a Log command to see if the buffer is properly populated?

```
Given (a base64 string):
  <value>QWJjMTIz</value>

Do (visual decode):
  :Log getline(1, '$')\<cr>
  f>lvt<
  \<space>btoa

Expect (decoded string):
  <value>Abc123</value>
```

**Comment by christianrondeau** [comment]
Thanks for your help! 

I deleted all tests but two, and added the log. Here's the result: https://travis-ci.org/christianrondeau/vim-base64/builds/169736815

The second buffer log is empty. If you want to look at the specific files: https://github.com/christianrondeau/vim-base64/tree/debug-travis/tests

**Comment by christianrondeau** [comment]
Quick update: it might be in *my* code, when I remove everything from `Do` except `gg` it works: https://travis-ci.org/christianrondeau/vim-base64/builds/170111951

I'll continue investigating and close if confirmed.

**Comment by christianrondeau** [comment]
Ok, after lots of investigating, I can repro and it is not related to my code:

https://travis-ci.org/christianrondeau/vim-base64/builds/170431021

Here is the repro:

    Given:
      Here is a value
    
    Do:
      wv2e
      coops!\<Esc>`[v`]h
    
    Expect (works):
      Here oops! value
    
    Given:
      This will not work
    
    Do:
      gg
    
    Expect (does not work):
      This will not work

The key here is:

    `[v`]

This is what breaks the test. Probably because vader is using visual selection itself? Note that if instead of using Given, I use *Insert Mode* (e.g. `iSomething`)  it works fine, even with the visual selection recall. 

I'll update the issue title, any idea where to go from there?

**Comment by junegunn** [comment]
Thanks for looking into this. This obviously seems like it's caused by a bug of Vim itself, as it's not reproducible with the latest build of Vim. With the hint you provided I was able to find the code that does not work as expected: https://github.com/junegunn/vader.vim/blob/f69ecb1/autoload/vader/window.vim#L110

It is supposed to delete only the last line of the buffer, but for some reason, it was deleting the first line as well. Interestingly, the issue can be avoided if we change it to an equivalent command `d _`. I'll push the fix.

**Comment by christianrondeau** [comment]
It looks like this issue is solved as shown in my test branch!

https://travis-ci.org/christianrondeau/vim-base64/builds/170615246

I appreciate you actually doing the fix, that's nice! It's not over for me though.  Even though I now see the output (better!) it still works on my machine but not on travis:  https://travis-ci.org/christianrondeau/vim-base64/builds/170617201

I'll try to figure it out first and reach back if it's not on my end. 

Thanks again for your help!
