### ISSUE TITLE
Returning to the file you are editing after closing results

### ISSUE THREAD

**Issue by w0rp** [junegunn/vader.vim#99]
I like to make some changes to a `.vader` file, and use the `:Vader` command to run the tests in the file. This works pretty well, and I can see the results in a new tab. However, if there are other tabs open, Vader can switch to some other tab after tests complete. Would it be possible to change the command so that Vader will remember which buffer you had open when you ran the tests, and then switch back to that buffer after the results are closed?

**Comment by junegunn** [comment]
Well, we can store the value of `tabpagenr()` before opening the vader tab, and go back to the tab when vader buffer is closed using autocmd. It's not impossible, but `tabpagenr()` changes according to the order of tabs, so the previous `tabpagenr()` may no longer point to the original tab. So we would need some heuristic to check if it's still the correct tab and optionally find the correct tab if it doesn't seem so. It's a bit of a hassle.

**Comment by w0rp** [comment]
We could perhaps store the window number, or maybe the buffer number, when Vader is run instead. Then we could find the window or tab to switch back to based on that information.

**Comment by justinmk** [comment]
@junegunn `win_getid()` is available in recent Vim/Nvim.

**Comment by junegunn** [comment]
Yeah. My point is that the solution is not clear-cut and it feels like too much of a hassle for a non-essential feature. FWIW, it should be possible to implement the scheme externally. A custom command that 1. remembers the current tab/window, 2. sets up a buffer-local autocmd to return to it (`autocmd FileType vader-result autocmd BufHidden <buffer> ...`) and 3. runs Vader.

**Comment by junegunn** [comment]
@justinmk Thanks, didn't know that. `win_getid()` + `win_id2tabwin()` combo should be very useful.

**Comment by w0rp** [comment]
Could you add an example into the README or some other help documentation describing how to do this, if you want this?

**Comment by junegunn** [comment]
@w0rp The behavior you requested is implemented in ceba9db.

**Comment by w0rp** [comment]
Cool, that's even better. Thanks again!
